### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mu-mandayam**
Murali Mandayam added his mid-term capstone project details.

### CODE REVIEW

**Comment by mu-mandayam** [comment]
Added details on MM's mid-term capstone project.

**Comment by mricos** [comment]
Hi Murali, getting close! Can you cut the summary in half and change the kaggle link to be a link on the work 'Kaggle' so the entire url does not show? I'm hoping for folks to be able to scan the list. Thank you, happy to help if this is becoming tedious.

**Comment by mricos** [comment]
Completed on ux305 via commandine merge.

**Comment by mricos** [comment]
Done on commandlne

**Pull request closed without merging**
